//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class clientes {
    
    private clientesCliente[] clienteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cliente", IsNullable=true)]
    public clientesCliente[] cliente {
        get {
            return this.clienteField;
        }
        set {
            this.clienteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class clientesCliente {
    
    private string codField;
    
    private string nifField;
    
    private string razonsField;
    
    private string codcondpField;
    
    private System.Nullable<decimal> limitrgField;
    
    private bool limitrgFieldSpecified;
    
    private string provField;
    
    private clientesClienteDim[] dimsField;
    
    private System.Nullable<uint> lrcompField;
    
    private bool lrcompFieldSpecified;
    
    private string[] viaspField;
    
    private string clasifcontableField;
    
    private System.Nullable<decimal> lsegcreditoField;
    
    private bool lsegcreditoFieldSpecified;
    
    private System.Nullable<System.DateTime> fchcadsegcredField;
    
    private bool fchcadsegcredFieldSpecified;
    
    private string tipoentidadField;
    
    private string sectorField;
    
    private System.Nullable<System.DateTime> fchaltaerpField;
    
    private bool fchaltaerpFieldSpecified;
    
    private System.Nullable<System.DateTime> fchinitactField;
    
    private bool fchinitactFieldSpecified;
    
    private string ind1Field;
    
    private string ind2Field;
    
    private string ind3Field;
    
    private string ind4Field;
    
    private string ind5Field;
    
    private string ind6Field;
    
    private string ind7Field;
    
    private string ind8Field;
    
    private string ind9Field;
    
    /// <remarks/>
    public string cod {
        get {
            return this.codField;
        }
        set {
            this.codField = value;
        }
    }
    
    /// <remarks/>
    public string nif {
        get {
            return this.nifField;
        }
        set {
            this.nifField = value;
        }
    }
    
    /// <remarks/>
    public string razons {
        get {
            return this.razonsField;
        }
        set {
            this.razonsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string codcondp {
        get {
            return this.codcondpField;
        }
        set {
            this.codcondpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> limitrg {
        get {
            return this.limitrgField;
        }
        set {
            this.limitrgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool limitrgSpecified {
        get {
            return this.limitrgFieldSpecified;
        }
        set {
            this.limitrgFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string prov {
        get {
            return this.provField;
        }
        set {
            this.provField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("dim")]
    public clientesClienteDim[] dims {
        get {
            return this.dimsField;
        }
        set {
            this.dimsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<uint> lrcomp {
        get {
            return this.lrcompField;
        }
        set {
            this.lrcompField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lrcompSpecified {
        get {
            return this.lrcompFieldSpecified;
        }
        set {
            this.lrcompFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("codvp")]
    public string[] viasp {
        get {
            return this.viaspField;
        }
        set {
            this.viaspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string clasifcontable {
        get {
            return this.clasifcontableField;
        }
        set {
            this.clasifcontableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> lsegcredito {
        get {
            return this.lsegcreditoField;
        }
        set {
            this.lsegcreditoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lsegcreditoSpecified {
        get {
            return this.lsegcreditoFieldSpecified;
        }
        set {
            this.lsegcreditoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> fchcadsegcred {
        get {
            return this.fchcadsegcredField;
        }
        set {
            this.fchcadsegcredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fchcadsegcredSpecified {
        get {
            return this.fchcadsegcredFieldSpecified;
        }
        set {
            this.fchcadsegcredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string tipoentidad {
        get {
            return this.tipoentidadField;
        }
        set {
            this.tipoentidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string sector {
        get {
            return this.sectorField;
        }
        set {
            this.sectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> fchaltaerp {
        get {
            return this.fchaltaerpField;
        }
        set {
            this.fchaltaerpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fchaltaerpSpecified {
        get {
            return this.fchaltaerpFieldSpecified;
        }
        set {
            this.fchaltaerpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> fchinitact {
        get {
            return this.fchinitactField;
        }
        set {
            this.fchinitactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fchinitactSpecified {
        get {
            return this.fchinitactFieldSpecified;
        }
        set {
            this.fchinitactFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind1 {
        get {
            return this.ind1Field;
        }
        set {
            this.ind1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind2 {
        get {
            return this.ind2Field;
        }
        set {
            this.ind2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind3 {
        get {
            return this.ind3Field;
        }
        set {
            this.ind3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind4 {
        get {
            return this.ind4Field;
        }
        set {
            this.ind4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind5 {
        get {
            return this.ind5Field;
        }
        set {
            this.ind5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind6 {
        get {
            return this.ind6Field;
        }
        set {
            this.ind6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind7 {
        get {
            return this.ind7Field;
        }
        set {
            this.ind7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind8 {
        get {
            return this.ind8Field;
        }
        set {
            this.ind8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ind9 {
        get {
            return this.ind9Field;
        }
        set {
            this.ind9Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class clientesClienteDim {
    
    private string ordenField;
    
    private string codelemField;
    
    private string codcritField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string orden {
        get {
            return this.ordenField;
        }
        set {
            this.ordenField = value;
        }
    }
    
    /// <remarks/>
    public string codelem {
        get {
            return this.codelemField;
        }
        set {
            this.codelemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codcrit {
        get {
            return this.codcritField;
        }
        set {
            this.codcritField = value;
        }
    }
}
