using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class ActivosFijos
    {
        public string IdActivo { get; set; }
        public string IdAdicion { get; set; }
        public string AfactivoDescripcion { get; set; }
        public string IdReferencia { get; set; }
        public string IdCo { get; set; }
        public string IdCcosto { get; set; }
        public string IdEmp { get; set; }
        public string IdGrupo1 { get; set; }
        public string IdGrupo2 { get; set; }
        public string IdGrupo3 { get; set; }
        public string IdGrupo4 { get; set; }
        public string IdGrupo5 { get; set; }
        public string IdUbica { get; set; }
        public string IdGrucon { get; set; }
        public string IdBarras { get; set; }
        public string FechaActivacion { get; set; }
        public string FechaUltDepre { get; set; }
        public string FechaUltAjusPaag { get; set; }
        public string FechaUltAvaluo { get; set; }
        public string FechaDarBaja { get; set; }
        public string IdProyecto { get; set; }
        public decimal? CostoAdqui { get; set; }
        public string IndAdicion { get; set; }
        public string IndEscaneado { get; set; }
        public string Abrev { get; set; }
        public string EmpOc { get; set; }
        public string CoOc { get; set; }
        public string TipoOc { get; set; }
        public string NroOc { get; set; }
        public string FechaOc { get; set; }
        public string TercOc { get; set; }
        public string TercSucOc { get; set; }
        public string Destec1 { get; set; }
        public string Destec2 { get; set; }
        public string Destec3 { get; set; }
        public string Destec4 { get; set; }
        public string Responsable { get; set; }
        public string FechaAdqui { get; set; }
        public string Estado { get; set; }
        public string Proced { get; set; }
        public string IndAjustable { get; set; }
        public string IndDepre { get; set; }
        public string MetodoDepre { get; set; }
        public string IndReserva { get; set; }
        public string Obs1Reserva { get; set; }
        public string Obs2Reserva { get; set; }
        public string Obs3Reserva { get; set; }
        public string Obs4Reserva { get; set; }
        public string EmpAct { get; set; }
        public string CoAct { get; set; }
        public string TipoAct { get; set; }
        public string NroAct { get; set; }
        public string NtdAct { get; set; }
        public string EmpAvaluo { get; set; }
        public string CoAvaluo { get; set; }
        public string TipoAvaluo { get; set; }
        public string FirmaAvaluo { get; set; }
        public string EmpDarBaja { get; set; }
        public string CoDarBaja { get; set; }
        public string TipoDarBaja { get; set; }
        public string NtdDarBaja { get; set; }
        public string Obs1DarBaja { get; set; }
        public string Obs2DarBaja { get; set; }
        public string Obs3DarBaja { get; set; }
        public string Obs4DarBaja { get; set; }
        public string MotivoDarBaja { get; set; }
        public decimal? UnidadDepre { get; set; }
        public decimal? AjusteUnidadDepre { get; set; }
        public decimal? PeriodosADepre { get; set; }
        public decimal? UnidadADepre { get; set; }
        public decimal? PorcSalvamento { get; set; }
        public decimal? NroPiezas { get; set; }
        public decimal? ValorSalvamento { get; set; }
        public decimal? PeriodosDepre { get; set; }
        public decimal? PeriodosSuspen { get; set; }
        public decimal? AjustePeriodosDepre { get; set; }
        public decimal? UnidadPteDepre { get; set; }
        public decimal? NroAvaluo { get; set; }
        public decimal? NtdAvaluo { get; set; }
        public decimal? ValorAvaluo { get; set; }
        public decimal? NroDarBaja { get; set; }
        public decimal? CostoAdquiAc { get; set; }
        public decimal? CostoAdquiAj { get; set; }
        public decimal? PaagCostoAdquiAc { get; set; }
        public decimal? PaagCostoAdquiAj { get; set; }
        public decimal? DepreAcumHistAc { get; set; }
        public decimal? DepreAcumHistAj { get; set; }
        public decimal? DepreAcumPaagAc { get; set; }
        public decimal? DepreAcumPaagAj { get; set; }
        public decimal? AjustPaagDepreAc { get; set; }
        public decimal? AjustPaagDepreAj { get; set; }
        public decimal? ValorizacionAc { get; set; }
        public decimal? ValorizacionAj { get; set; }
        public decimal? ProvisionAc { get; set; }
        public decimal? ProvisionAj { get; set; }
        public decimal? AjustePeriodADepre { get; set; }
    }
}
