using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class AutoventaInvfisico
    {
        public string LapsoReg { get; set; }
        public string FechaReg { get; set; }
        public string IdTipoReg { get; set; }
        public string IdCoBodega { get; set; }
        public string IdLocalBodega { get; set; }
        public string IdItems { get; set; }
        public string IdExtitm { get; set; }
        public decimal? InvIni { get; set; }
        public decimal? EntTrasl01 { get; set; }
        public decimal? EntCarro01 { get; set; }
        public decimal? EntDepos01 { get; set; }
        public decimal? VtaCarga01 { get; set; }
        public decimal? VtaEstac01 { get; set; }
        public decimal? VtaCarbu01 { get; set; }
        public decimal? SalConsu01 { get; set; }
        public decimal? TraLadin01 { get; set; }
        public decimal? TraDepos01 { get; set; }
        public decimal? DevMayor01 { get; set; }
        public decimal? EntPlant02 { get; set; }
        public decimal? VtaCarga02 { get; set; }
        public decimal? VtaCarbu02 { get; set; }
        public decimal? DevPlant02 { get; set; }
        public decimal? SalConsu02 { get; set; }
        public decimal? SalEc02 { get; set; }
        public decimal? EntMayor03 { get; set; }
        public decimal? EntCarro03 { get; set; }
        public decimal? EntRend03 { get; set; }
        public decimal? VtaCarga03 { get; set; }
        public decimal? VtaEstac03 { get; set; }
        public decimal? VtaCarbu03 { get; set; }
        public decimal? SalConsu03 { get; set; }
        public decimal? DevMayor03 { get; set; }
        public decimal? SalRend03 { get; set; }
        public decimal? SalEc03 { get; set; }
        public decimal? ComEcope04 { get; set; }
        public decimal? ComOtros04 { get; set; }
        public decimal? EntRegio04 { get; set; }
        public decimal? EntCarro04 { get; set; }
        public decimal? VtaGrane04 { get; set; }
        public decimal? TraMinor04 { get; set; }
        public decimal? SalRegio04 { get; set; }
        public decimal? ComEcope05 { get; set; }
        public decimal? ComOtros05 { get; set; }
        public decimal? EntRegio05 { get; set; }
        public decimal? Ventas05 { get; set; }
        public decimal? SalConsu05 { get; set; }
        public decimal? SalRegio05 { get; set; }
        public decimal? SalEc05 { get; set; }
        public decimal? ComEcope06 { get; set; }
        public decimal? ComOtros06 { get; set; }
        public decimal? Ventas06 { get; set; }
        public decimal? SalConsu06 { get; set; }
        public decimal? SalEc06 { get; set; }
        public decimal? EntTalle07 { get; set; }
        public decimal? EntDepos07 { get; set; }
        public decimal? EntExpen07 { get; set; }
        public decimal? EntRegio07 { get; set; }
        public decimal? EntCambi07 { get; set; }
        public decimal? EntPrest07 { get; set; }
        public decimal? EntConso07 { get; set; }
        public decimal? EntCinsa07 { get; set; }
        public decimal? EntCompr07 { get; set; }
        public decimal? SalTalle07 { get; set; }
        public decimal? SalDepos07 { get; set; }
        public decimal? SalExpen07 { get; set; }
        public decimal? SalRegio07 { get; set; }
        public decimal? SalCambi07 { get; set; }
        public decimal? SalPrest07 { get; set; }
        public decimal? SalConso07 { get; set; }
        public decimal? Ventas07 { get; set; }
        public decimal? SalBaja07 { get; set; }
        public decimal? EntPlant08 { get; set; }
        public decimal? EntExpen08 { get; set; }
        public decimal? EntCambi08 { get; set; }
        public decimal? EntPrest08 { get; set; }
        public decimal? SalPlant08 { get; set; }
        public decimal? SalExpen08 { get; set; }
        public decimal? SalCambi08 { get; set; }
        public decimal? SalPrest08 { get; set; }
        public decimal? Ventas08 { get; set; }
        public decimal? ComCinsa09 { get; set; }
        public decimal? OtrCompr09 { get; set; }
        public decimal? EntConso09 { get; set; }
        public decimal? EntRegio09 { get; set; }
        public decimal? SalConso09 { get; set; }
        public decimal? SalRegio09 { get; set; }
        public decimal? Ventas09 { get; set; }
        public decimal? SalBaja09 { get; set; }
        public decimal? ComCinsa10 { get; set; }
        public decimal? OtrCompr10 { get; set; }
        public decimal? EntConso10 { get; set; }
        public decimal? Ventas10 { get; set; }
        public decimal? SalBaja10 { get; set; }
        public decimal? SalConso10 { get; set; }
        public decimal? OtrasEntradas { get; set; }
        public decimal? OtrasSalidas { get; set; }
        public decimal? InvFisico { get; set; }
        public decimal? SaldoTran { get; set; }
        public decimal? EntTran { get; set; }
        public decimal? SalTran { get; set; }
        public decimal? EntRend05 { get; set; }
        public decimal? SalRend05 { get; set; }
        public decimal? InvfisProc { get; set; }
        public string EstadoInvfis { get; set; }
        public string EstadoTrans { get; set; }
        public string FechaGen { get; set; }
    }
}
