using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class CmmovimientoVentas
    {
        public string LapsoDoc { get; set; }
        public string IdEmp { get; set; }
        public string IdCo { get; set; }
        public string IdTipdoc { get; set; }
        public string DocumentoFc { get; set; }
        public string FechaDcto { get; set; }
        public string IdTerc { get; set; }
        public string IdSuc { get; set; }
        public string DocRmEmp { get; set; }
        public string DocRmCo { get; set; }
        public string DocRmTipo { get; set; }
        public string DocumentoRm { get; set; }
        public string FechaRm { get; set; }
        public string DocPdCo { get; set; }
        public string DocPdTipo { get; set; }
        public string DocumentoPd { get; set; }
        public string DocAltEmp { get; set; }
        public string DocAltCo { get; set; }
        public string DocAltTip { get; set; }
        public string DocumentoAlt { get; set; }
        public string IdFPago { get; set; }
        public string IdVendedor { get; set; }
        public string IdItem { get; set; }
        public string IdExtItm { get; set; }
        public string IdTalla { get; set; }
        public string IdSerial { get; set; }
        public string IdConcepto { get; set; }
        public string IdMotivo { get; set; }
        public string IdUnidad { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? CantidadCap { get; set; }
        public decimal? PrecioUni { get; set; }
        public decimal? DsctoNetos { get; set; }
        public decimal? TotVenta { get; set; }
        public decimal? TotBruto { get; set; }
        public decimal? ImpNetos { get; set; }
        public decimal? CostoVta { get; set; }
        public decimal? Rentabil { get; set; }
        public decimal? PrecioUniMe { get; set; }
        public decimal? DsctoNetosMe { get; set; }
        public decimal? TotVentaMe { get; set; }
        public decimal? ImpNetosMe { get; set; }
        public string IdLocal { get; set; }
        public decimal? Cantidad2 { get; set; }
        public string IdLote { get; set; }
        public string IdUbicacion { get; set; }
        public string IdLipre { get; set; }
        public string IdLides { get; set; }
        public string IdCtaCxc { get; set; }
        public string IdCoCxc { get; set; }
        public string IdCtaVen { get; set; }
        public string IdCoVen { get; set; }
        public string IdCtaCco { get; set; }
        public string IdCoCco { get; set; }
        public string Ccosto { get; set; }
        public string Proyecto { get; set; }
        public string NroReq { get; set; }
        public string IdOrides { get; set; }
        public decimal? PorcDscto1 { get; set; }
        public decimal? PorcDscto2 { get; set; }
        public decimal? PorcDsctoGl1 { get; set; }
        public decimal? PorcDsctoGl2 { get; set; }
        public decimal? PorcTasaIva { get; set; }
        public decimal? CantidadTalla1 { get; set; }
        public decimal? CantidadTalla2 { get; set; }
        public decimal? CantidadTalla3 { get; set; }
        public decimal? CantidadTalla4 { get; set; }
        public decimal? CantidadTalla5 { get; set; }
        public decimal? CantidadTalla6 { get; set; }
        public decimal? CantidadTalla7 { get; set; }
        public decimal? CantidadTalla8 { get; set; }
        public decimal? CantidadTalla9 { get; set; }
        public decimal? CantidadTalla10 { get; set; }
        public string Detalle1 { get; set; }
        public string Detalle2 { get; set; }
        public string Detalle3 { get; set; }
        public string Detalle4 { get; set; }
        public string CargueCo { get; set; }
        public string CargueNro { get; set; }
        public string FechaVctoLote { get; set; }
        public string IndAutoventa { get; set; }
        public string NomCliContado { get; set; }
        public string NitCliContado { get; set; }
        public string TipIdeContado { get; set; }
        public decimal? Peso { get; set; }
        public decimal? Volumen { get; set; }
        public string FechaGen { get; set; }
        public string IdGruloc { get; set; }
        public string IdTercFa { get; set; }
        public string IdSucFa { get; set; }
        public string NombreFa { get; set; }
        public string IdVendCc { get; set; }
        public string NombreVend { get; set; }
        public string IdCargue { get; set; }
        public string IdClater1 { get; set; }
        public string IdClater2 { get; set; }
        public string IdClater { get; set; }
        public string FechaPd { get; set; }
        public string DctoFact { get; set; }
        public string AnoFact { get; set; }
        public string DetalleRm1 { get; set; }
        public string DetalleRm2 { get; set; }
        public string DetalleRm3 { get; set; }
        public string DetalleRm4 { get; set; }
        public string DetalleRm5 { get; set; }
        public string DetalleRm6 { get; set; }
        public string DetalleRm7 { get; set; }
        public string DetalleRm8 { get; set; }
        public string DetalleRm9 { get; set; }
        public string DetalleRm10 { get; set; }
        public string IdTercMov { get; set; }
        public string IdSucMov { get; set; }
        public string NombreTercMov { get; set; }
        public decimal? VlrtotBruMe { get; set; }
        public decimal? VlrdesLinea1Me { get; set; }
        public decimal? VlrdesLinea2Me { get; set; }
        public decimal? VlrdesGlobal1Me { get; set; }
        public decimal? VlrdesGlobal2Me { get; set; }
        public decimal? VlrivaMe { get; set; }
        public decimal? Vlrimpoconsumo1Me { get; set; }
        public decimal? Vlrimpoconsumo2Me { get; set; }
        public decimal? VlrnetMe { get; set; }
        public string DetalleDoc { get; set; }
        public string OrdenCompra { get; set; }
        public decimal? Vlrimpoconsumo1 { get; set; }
        public decimal? Vlrimpoconsumo2 { get; set; }
        public string NtdTalla { get; set; }
        public string IdTercProv { get; set; }
        public decimal? VlrdesLinea1 { get; set; }
        public decimal? VlrdesLinea2 { get; set; }
        public decimal? VlrdesGlobal1 { get; set; }
        public decimal? VlrdesGlobal2 { get; set; }
        public string CiudadDespCod { get; set; }
        public string CiudadDespDesc { get; set; }
        public string DirDesp { get; set; }
        public string IdCodbar { get; set; }
        public string DocAlterno { get; set; }
        public string FechaVctodoc { get; set; }
        public string CodigoSerial { get; set; }
        public string FecCierreCar { get; set; }
        public decimal? VtaGravada { get; set; }
        public decimal? VtaExenta { get; set; }
        public string CargueEstado { get; set; }
        public string HoraIngMovrm { get; set; }
        public string FechaFv { get; set; }
        public string HoraIngFv { get; set; }
    }
}
