using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class CmmovimientoPdv
    {
        public string LapsoDoc { get; set; }
        public string IdCo { get; set; }
        public string IdCaja { get; set; }
        public string FechaDcto { get; set; }
        public string IdTerc { get; set; }
        public string IdSuc { get; set; }
        public string DocumentoDocfc { get; set; }
        public string IdOrigen { get; set; }
        public string IdCajero { get; set; }
        public string IdTurno { get; set; }
        public string IdOrden { get; set; }
        public string IdRef { get; set; }
        public string IdNroPersonasAnt { get; set; }
        public string IdVendCc { get; set; }
        public string IdVend { get; set; }
        public string IdNomcli { get; set; }
        public string IdNitcli { get; set; }
        public string IdTipoIdent { get; set; }
        public string IdCondPago { get; set; }
        public string IdFormaPago { get; set; }
        public string IdModoCredito { get; set; }
        public string Periodicidad { get; set; }
        public string NroCuotas { get; set; }
        public string FechaVctoFija { get; set; }
        public string IdAmbiente { get; set; }
        public string IdMoneda { get; set; }
        public string IdEstado { get; set; }
        public string DoctoAcumulacion { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFinal { get; set; }
        public string DoctoPag { get; set; }
        public string Detalle { get; set; }
        public string HoraEntrega { get; set; }
        public string IdItem { get; set; }
        public string IdItmext { get; set; }
        public string IdTalla { get; set; }
        public string IdLocal { get; set; }
        public string IdCpto { get; set; }
        public string IdMotivo { get; set; }
        public string IdCodbar { get; set; }
        public string IdUnidad { get; set; }
        public string IdLote { get; set; }
        public string FechaVctoLote { get; set; }
        public string IdUbicacion { get; set; }
        public string IdLipre { get; set; }
        public string IdLides { get; set; }
        public string IdCuentaCxc { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? CantidadCap { get; set; }
        public decimal? Cantidad2 { get; set; }
        public decimal? CantidadPeso { get; set; }
        public decimal? CantidadVol { get; set; }
        public decimal? PrecioUni { get; set; }
        public decimal? DsctoNetos { get; set; }
        public decimal? VenNetas { get; set; }
        public decimal? VlrtotBru { get; set; }
        public decimal? ImpNetos { get; set; }
        public decimal? TotCosto { get; set; }
        public decimal? TotRenta { get; set; }
        public decimal? PrecioUniMe { get; set; }
        public decimal? DsctoNetosMe { get; set; }
        public decimal? VenNetasMe { get; set; }
        public decimal? ImpNetosMe { get; set; }
        public decimal? Dscto1 { get; set; }
        public decimal? Dscto2 { get; set; }
        public decimal? DsctoGlobal1 { get; set; }
        public decimal? DsctoGlobal2 { get; set; }
        public decimal? TasaIva { get; set; }
        public decimal? CantTalla1 { get; set; }
        public decimal? CantTalla2 { get; set; }
        public decimal? CantTalla3 { get; set; }
        public decimal? CantTalla4 { get; set; }
        public decimal? CantTalla5 { get; set; }
        public decimal? CantTalla6 { get; set; }
        public decimal? CantTalla7 { get; set; }
        public decimal? CantTalla8 { get; set; }
        public decimal? CantTalla9 { get; set; }
        public decimal? CantTalla10 { get; set; }
        public string IndPrecioMod { get; set; }
        public string NroComanda { get; set; }
        public decimal? Puntos { get; set; }
        public string Orden { get; set; }
        public string Termino { get; set; }
        public string DescGenerico1 { get; set; }
        public string IdEmpFc { get; set; }
        public string IdCoFc { get; set; }
        public string IdTipdocFc { get; set; }
        public string DocumentoFc { get; set; }
        public string FechaGen { get; set; }
        public string IdGruloc { get; set; }
        public string HoraIni { get; set; }
        public string HoraFin { get; set; }
        public string VendCc { get; set; }
        public string VendCcDesc { get; set; }
        public decimal? Vlrimpcon1 { get; set; }
        public decimal? Vlrimpcon2 { get; set; }
        public string ConsecutivoDoc { get; set; }
        public string ZonaVarcli { get; set; }
    }
}
