using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class CmresumenInventario
    {
        public string IdCo { get; set; }
        public string IdLocal { get; set; }
        public string LapsoDoc { get; set; }
        public string IdItem { get; set; }
        public string IdExtItm { get; set; }
        public string IdTalla { get; set; }
        public string CuentaInv { get; set; }
        public string CoInv { get; set; }
        public string Ccosto { get; set; }
        public string Proyecto { get; set; }
        public string NroReq { get; set; }
        public string IdOrides { get; set; }
        public decimal? CanExisIni { get; set; }
        public decimal? CanExisEnt { get; set; }
        public decimal? CanExisSal { get; set; }
        public decimal? CanExisFin { get; set; }
        public decimal? Can2ExisIni { get; set; }
        public decimal? Can2ExisEnt { get; set; }
        public decimal? Can2ExisSal { get; set; }
        public decimal? Can2ExisFin { get; set; }
        public decimal? CanStocMin { get; set; }
        public decimal? CanStocMax { get; set; }
        public decimal? VlrCostIni { get; set; }
        public decimal? VlrCostEnt { get; set; }
        public decimal? VlrCostSal { get; set; }
        public decimal? VlrCostFin { get; set; }
        public decimal? VlrCompras { get; set; }
        public decimal? VlrVentas { get; set; }
        public decimal? CanExisIni1 { get; set; }
        public decimal? CanExisEnt1 { get; set; }
        public decimal? CanExisSal1 { get; set; }
        public decimal? CanExisFin1 { get; set; }
        public decimal? CanExisIni2 { get; set; }
        public decimal? CanExisEnt2 { get; set; }
        public decimal? CanExisSal2 { get; set; }
        public decimal? CanExisFin2 { get; set; }
        public decimal? CanExisIni3 { get; set; }
        public decimal? CanExisEnt3 { get; set; }
        public decimal? CanExisSal3 { get; set; }
        public decimal? CanExisFin3 { get; set; }
        public decimal? CanExisIni4 { get; set; }
        public decimal? CanExisEnt4 { get; set; }
        public decimal? CanExisSal4 { get; set; }
        public decimal? CanExisFin4 { get; set; }
        public decimal? CanExisIni5 { get; set; }
        public decimal? CanExisEnt5 { get; set; }
        public decimal? CanExisSal5 { get; set; }
        public decimal? CanExisFin5 { get; set; }
        public decimal? CanExisIni6 { get; set; }
        public decimal? CanExisEnt6 { get; set; }
        public decimal? CanExisSal6 { get; set; }
        public decimal? CanExisFin6 { get; set; }
        public decimal? CanExisIni7 { get; set; }
        public decimal? CanExisEnt7 { get; set; }
        public decimal? CanExisSal7 { get; set; }
        public decimal? CanExisFin7 { get; set; }
        public decimal? CanExisIni8 { get; set; }
        public decimal? CanExisEnt8 { get; set; }
        public decimal? CanExisSal8 { get; set; }
        public decimal? CanExisFin8 { get; set; }
        public decimal? CanExisIni9 { get; set; }
        public decimal? CanExisEnt9 { get; set; }
        public decimal? CanExisSal9 { get; set; }
        public decimal? CanExisFin9 { get; set; }
        public decimal? CanExisIni10 { get; set; }
        public decimal? CanExisEnt10 { get; set; }
        public decimal? CanExisSal10 { get; set; }
        public decimal? CanExisFin10 { get; set; }
        public string FechaUltcom { get; set; }
        public string FechaUltvta { get; set; }
        public string FechaUltent { get; set; }
        public string FechaUltsal { get; set; }
        public string FechaUltcon { get; set; }
        public decimal? CantVendida { get; set; }
        public decimal? CantComprada { get; set; }
        public decimal? CostoTot { get; set; }
        public decimal? CostoUni { get; set; }
        public decimal? Peso { get; set; }
        public decimal? Volumen { get; set; }
        public string FechaGen { get; set; }
        public string IdUbicacion { get; set; }
        public string IdOridesEs { get; set; }
        public string IdGruloc { get; set; }
        public string IdLote { get; set; }
        public string FechaVctoLote { get; set; }
        public string IdClasif { get; set; }
        public decimal? TiempoSeg { get; set; }
        public decimal? TiempoRep { get; set; }
        public decimal? PeriodoCubrim { get; set; }
        public decimal? PuntoPed { get; set; }
        public decimal? VlrNivelMin { get; set; }
        public decimal? VlrNivelMax { get; set; }
        public string IdTercProv { get; set; }
        public decimal? UltCosto { get; set; }
        public decimal? CanDisponible { get; set; }
        public string IdCodbar { get; set; }
        public string FechaUltsalmov { get; set; }
    }
}
