using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class HojasDeVida
    {
        public string Empleado { get; set; }
        public string Sucursal { get; set; }
        public string Nit { get; set; }
        public string CiudadExpedicion { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string TipoIdentifica { get; set; }
        public string Estado { get; set; }
        public string FechaCreacion { get; set; }
        public string CiudadCorresp { get; set; }
        public string Direccion1 { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string Barrio { get; set; }
        public string Email { get; set; }
        public string DescCiudadNacimiento { get; set; }
        public string FechaIngresoEmpleado { get; set; }
        public string FechaNacimientoEmpleado { get; set; }
        public string CiudadNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public string CiuuEmpleado { get; set; }
        public string Empresa { get; set; }
        public string NumeroDeContrato { get; set; }
        public decimal? Salario { get; set; }
        public decimal? Cantidad { get; set; }
        public string TipoNomina { get; set; }
        public string IdCo { get; set; }
        public string IdCcosto { get; set; }
        public string FechaRetiro { get; set; }
        public string FechaIngreso { get; set; }
        public string FechaContHa { get; set; }
        public string FechaPrimHa { get; set; }
        public string FechaVacaHa { get; set; }
        public string FechaUltAum { get; set; }
        public string IndAux { get; set; }
        public string Pension { get; set; }
        public string DescPension { get; set; }
        public string Eps { get; set; }
        public string DescEps { get; set; }
        public string Arp { get; set; }
        public string DescArp { get; set; }
        public string Afpv { get; set; }
        public string DescAfpv { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
        public string IndRegLab { get; set; }
        public string IndSalInt { get; set; }
        public string Fondo { get; set; }
        public string Caja { get; set; }
        public string DescCajaCompensacion { get; set; }
        public string IndSubFam { get; set; }
        public string IdProyecto { get; set; }
        public string IdCargo { get; set; }
        public string ObservacionesContrato { get; set; }
        public string GrupoDeEmpleados { get; set; }
        public string Clase { get; set; }
        public string FormaDePago { get; set; }
        public string CodigoHorario { get; set; }
        public string Huc { get; set; }
        public string CodigoTipoCotizante { get; set; }
        public string IndSubtipoCotizante { get; set; }
        public string IndExtranjeroPensionado { get; set; }
        public string MotivoRetiro { get; set; }
        public string GrupoSanguineo { get; set; }
        public string LimitacionFisica { get; set; }
        public string MarcaCicatriz { get; set; }
        public string NroRegistroCivil { get; set; }
        public string NotariaRegistroCivil { get; set; }
        public string CiudadRegistroCivil { get; set; }
        public string NroLibretaMilitar { get; set; }
        public string ClaseLibretaMilitar { get; set; }
        public string DistLibretaMilitar { get; set; }
        public string NroPasaporte { get; set; }
        public string CiudadPasaporte { get; set; }
        public string NroLicConduccion { get; set; }
        public string CatLicConduccion { get; set; }
        public string ExpLicConduccion { get; set; }
        public string Emergencia { get; set; }
        public string ClaseSocial { get; set; }
        public string PersonasACargo { get; set; }
        public string Peso { get; set; }
        public string Altura { get; set; }
        public string ColorPiel { get; set; }
        public string NombreCargo { get; set; }
        public string EstadoContrato { get; set; }
        public string NombreEmpresa { get; set; }
        public string CodigoMotivoRetiro { get; set; }
        public string Tele2 { get; set; }
    }
}
