using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class MovimientoAutoventas
    {
        public string LapsoDoc { get; set; }
        public string IdEmp { get; set; }
        public string DocInvCo { get; set; }
        public string DocInvTipo { get; set; }
        public string DocumentoInv { get; set; }
        public string DocumentoAlt { get; set; }
        public string FechaDoc { get; set; }
        public string IndEs { get; set; }
        public string IdLocal { get; set; }
        public string IdItem { get; set; }
        public string IdExtItm { get; set; }
        public string IdTalla { get; set; }
        public string IdRefer { get; set; }
        public string IdCodbar { get; set; }
        public string IdConcepto { get; set; }
        public string IdMotivo { get; set; }
        public string UnimedCap { get; set; }
        public decimal? Cantidad1 { get; set; }
        public decimal? CostoUni { get; set; }
        public decimal? Costot { get; set; }
        public decimal? Cantidad2 { get; set; }
        public string Lote { get; set; }
        public string FechaVctoLote { get; set; }
        public string Ubicacion { get; set; }
        public string IdCoMov { get; set; }
        public string IdCateg { get; set; }
        public string IdLinea1 { get; set; }
        public string IdLinea2 { get; set; }
        public string IdLinea { get; set; }
        public string IdLinea16 { get; set; }
        public string IdLinea36 { get; set; }
        public string IdLinea56 { get; set; }
        public string IdGrupo1 { get; set; }
        public string IdGrupo2 { get; set; }
        public string IdGrupo { get; set; }
        public string IdGrupo16 { get; set; }
        public string IdGrupo36 { get; set; }
        public string IdGrupo56 { get; set; }
        public string IdGrucon { get; set; }
        public string IdCricla1 { get; set; }
        public string IdCricla2 { get; set; }
        public string IdCricla3 { get; set; }
        public string IdCricla4 { get; set; }
        public decimal? Peso { get; set; }
        public decimal? Volumen { get; set; }
        public string IdCtaInv { get; set; }
        public string IdCtaInvContra { get; set; }
        public string IdCcosto { get; set; }
        public string IdProyecto { get; set; }
        public decimal? CantTalla1 { get; set; }
        public decimal? CantTalla2 { get; set; }
        public decimal? CantTalla3 { get; set; }
        public decimal? CantTalla4 { get; set; }
        public decimal? CantTalla5 { get; set; }
        public decimal? CantTalla6 { get; set; }
        public decimal? CantTalla7 { get; set; }
        public decimal? CantTalla8 { get; set; }
        public decimal? CantTalla9 { get; set; }
        public decimal? CantTalla10 { get; set; }
        public string CargueCo { get; set; }
        public string CargueNro { get; set; }
        public string FechaGen { get; set; }
        public string IdEstado { get; set; }
        public string IdVehiculo { get; set; }
        public string IdTercCond { get; set; }
        public string IdSucCond { get; set; }
        public string IdTercResp { get; set; }
        public string IdSucResp { get; set; }
        public string IdTercAyu1 { get; set; }
        public string IdSucAyu1 { get; set; }
        public string IdTercAyu2 { get; set; }
        public string IdSucAyu2 { get; set; }
        public string IdTercAyu3 { get; set; }
        public string IdSucAyu3 { get; set; }
        public string IdTercAyu4 { get; set; }
        public string IdSucAyu4 { get; set; }
        public string IdLipre { get; set; }
        public decimal? VlrtotCargue { get; set; }
        public decimal? VlrtotVenta { get; set; }
        public decimal? VlrvenCredito { get; set; }
        public decimal? VlrvenContado { get; set; }
        public decimal? VlrrecCartera { get; set; }
        public decimal? VlrrecCuadre { get; set; }
        public decimal? VlrrecDiferen { get; set; }
        public string Deta1 { get; set; }
        public string Deta2 { get; set; }
        public string Deta3 { get; set; }
        public string Deta4 { get; set; }
        public string IdEmpCuadre { get; set; }
        public string IdCoCuadre { get; set; }
        public string IdTipoCuadre { get; set; }
        public string IdNroCuadre { get; set; }
        public string IdFechaPys { get; set; }
        public string IdEmpDocin { get; set; }
        public string IdCoDocin { get; set; }
        public string IdTipoDocin { get; set; }
        public string IdNroDocin { get; set; }
        public string IdTercFac { get; set; }
        public string IdSucFac { get; set; }
        public string IdRuta { get; set; }
        public string IdLiqFlete { get; set; }
    }
}
