using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class MovimientoCompras
    {
        public string LapsoDoc { get; set; }
        public string IdEmp { get; set; }
        public string IdCo { get; set; }
        public string IdTipdoc { get; set; }
        public string DocEaEmp { get; set; }
        public string DocEaCo { get; set; }
        public string DocEaTipo { get; set; }
        public string DocumentoEa { get; set; }
        public string DocFpEmp { get; set; }
        public string DocFpCo { get; set; }
        public string DocFpTipo { get; set; }
        public string DocumentoFp { get; set; }
        public string DocCsEmp { get; set; }
        public string DocCsCo { get; set; }
        public string DocCsTipo { get; set; }
        public string DocumentoCs { get; set; }
        public string FechaDcto { get; set; }
        public string IdTerc { get; set; }
        public string IdSuc { get; set; }
        public string DocOcEmp { get; set; }
        public string DocOcCo { get; set; }
        public string DocOcTipo { get; set; }
        public string DocumentoOc { get; set; }
        public string IdComprador { get; set; }
        public string IdItem { get; set; }
        public string IdExtItm { get; set; }
        public string IdTalla { get; set; }
        public string IdRefer { get; set; }
        public string IdTipo { get; set; }
        public string IdLinea1 { get; set; }
        public string IdLinea2 { get; set; }
        public string IdLinea { get; set; }
        public string IdLinea16 { get; set; }
        public string IdLinea36 { get; set; }
        public string IdLinea56 { get; set; }
        public string IdConcepto { get; set; }
        public string IdMotivo { get; set; }
        public string IdUnidad { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? PrecioUni { get; set; }
        public decimal? DsctoNetos { get; set; }
        public decimal? TotCompra { get; set; }
        public decimal? ImpNetos { get; set; }
        public decimal? PrecioUniMe { get; set; }
        public decimal? DsctoNetosMe { get; set; }
        public decimal? TotCompraMe { get; set; }
        public decimal? ImpNetosMe { get; set; }
        public string IdClater1 { get; set; }
        public string IdClater2 { get; set; }
        public string IdClater { get; set; }
        public string IdGrupo1 { get; set; }
        public string IdGrupo2 { get; set; }
        public string IdGrupo { get; set; }
        public string IdGrupo16 { get; set; }
        public string IdGrupo36 { get; set; }
        public string IdGrupo56 { get; set; }
        public string IdGrucon { get; set; }
        public string IdCricla1 { get; set; }
        public string IdCricla2 { get; set; }
        public string IdCricla3 { get; set; }
        public string IdCricla4 { get; set; }
        public string Descripcion2 { get; set; }
        public string IdLocal { get; set; }
        public decimal? Cantidad2 { get; set; }
        public decimal? CantidadPeso { get; set; }
        public decimal? CantidadVol { get; set; }
        public string IdLote { get; set; }
        public string FechaVctoLote { get; set; }
        public string IdUbicacion { get; set; }
        public string IdCtaCxp { get; set; }
        public string IdCoCxp { get; set; }
        public string Ccosto { get; set; }
        public string GrupoCcosto { get; set; }
        public string CodigoNiv1 { get; set; }
        public string CodigoNiv2 { get; set; }
        public string CodigoNiv3 { get; set; }
        public string Proyecto { get; set; }
        public string NroReq { get; set; }
        public string IdOrides { get; set; }
        public decimal? CantidadTalla1 { get; set; }
        public decimal? CantidadTalla2 { get; set; }
        public decimal? CantidadTalla3 { get; set; }
        public decimal? CantidadTalla4 { get; set; }
        public decimal? CantidadTalla5 { get; set; }
        public decimal? CantidadTalla6 { get; set; }
        public decimal? CantidadTalla7 { get; set; }
        public decimal? CantidadTalla8 { get; set; }
        public decimal? CantidadTalla9 { get; set; }
        public decimal? CantidadTalla10 { get; set; }
        public string FechaGen { get; set; }
        public string IdGruloc { get; set; }
        public decimal? CantidadEmp { get; set; }
        public string DetalleItem { get; set; }
        public string CmoridesIndTipo { get; set; }
        public string NombreVend { get; set; }
        public decimal? CantSol { get; set; }
        public string AnoDoc { get; set; }
        public decimal? Impocomsumos { get; set; }
        public string FechaOc { get; set; }
    }
}
