using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class MovimientoContable
    {
        public string IdEmp { get; set; }
        public string DocFcCo { get; set; }
        public string DocFcTipo { get; set; }
        public string DocumentoFc { get; set; }
        public string Terc { get; set; }
        public string Suc { get; set; }
        public string FechaDoc { get; set; }
        public string Tipocta { get; set; }
        public string IdTipocta { get; set; }
        public string IdCtaniv1 { get; set; }
        public string IdCtaniv2 { get; set; }
        public string IdCtaniv3 { get; set; }
        public string IdCtaniv4 { get; set; }
        public string IdCtaniv5 { get; set; }
        public string IdCtaniv6 { get; set; }
        public string IdCtaniv7 { get; set; }
        public string IdCtaniv8 { get; set; }
        public string IdCuenta { get; set; }
        public string IdGpocco { get; set; }
        public string IdCconiv1 { get; set; }
        public string IdCconiv2 { get; set; }
        public string IdCconiv3 { get; set; }
        public string IdCconiv4 { get; set; }
        public string IdCconiv5 { get; set; }
        public string IdCconiv6 { get; set; }
        public string IdCconiv7 { get; set; }
        public string IdCconiv8 { get; set; }
        public string IdCcosto { get; set; }
        public string CoMov { get; set; }
        public string LapsoDoc { get; set; }
        public string Detalle1 { get; set; }
        public string Detalle2 { get; set; }
        public string IdProyecto { get; set; }
        public string IdTipocptofe { get; set; }
        public string IdCptofeniv1 { get; set; }
        public string IdCptofeniv2 { get; set; }
        public string IdCptofeniv3 { get; set; }
        public string IdCptofeniv4 { get; set; }
        public string Cptofe { get; set; }
        public string DocConcTipo { get; set; }
        public string DConciliacion { get; set; }
        public string DocCruTipo { get; set; }
        public string DCruce { get; set; }
        public string DocCruCuota { get; set; }
        public string IdVendedor { get; set; }
        public string FechaVcto { get; set; }
        public string DocProTipo { get; set; }
        public string DProveedor { get; set; }
        public string Moneda { get; set; }
        public string Caja { get; set; }
        public string CtaBanco { get; set; }
        public string Naturaleza { get; set; }
        public string IndModo { get; set; }
        public string MedPago { get; set; }
        public string IdRecaudo { get; set; }
        public string DocRecBanco { get; set; }
        public string DocRecCheque { get; set; }
        public string IdItem { get; set; }
        public string IdExtItm { get; set; }
        public decimal? CantItem { get; set; }
        public string IdActivo { get; set; }
        public string DocActAdi { get; set; }
        public string CodBancoPro { get; set; }
        public string DesBancoPro { get; set; }
        public string DocAltTipo { get; set; }
        public string DAlterno { get; set; }
        public string Unineg { get; set; }
        public decimal? ValorDeb { get; set; }
        public decimal? ValorCre { get; set; }
        public decimal? ValorDebMe { get; set; }
        public decimal? ValorCreMe { get; set; }
        public decimal? TasaConver { get; set; }
        public decimal? TasaCambio { get; set; }
        public decimal? TasaImpret { get; set; }
        public decimal? TasaBseimp { get; set; }
        public decimal? BaseIvaret { get; set; }
        public decimal? Cantidad { get; set; }
        public string FechaGen { get; set; }
        public string IdGpoProyec { get; set; }
        public string TercProyec { get; set; }
        public string SucTercProyec { get; set; }
        public string IdVendTerc { get; set; }
        public string VendTercDesc { get; set; }
        public string DetalleDoc { get; set; }
        public string IdTercDoc { get; set; }
        public string IdSucDoc { get; set; }
        public string DescTercDoc { get; set; }
        public string AnoFact { get; set; }
        public string IdGpoCcosto { get; set; }
        public string FechaRecaudo { get; set; }
        public string UsuarioIng { get; set; }
        public string HoraIng { get; set; }
        public string FechaIng { get; set; }
        public string UsuarioMod { get; set; }
        public string HoraMod { get; set; }
        public string FechaMod { get; set; }
        public string UsuarioAnu { get; set; }
        public string HoraAnu { get; set; }
        public string FechaAnu { get; set; }
        public string FechaDocCxc { get; set; }
        public string VencobDoc { get; set; }
        public string CodVendDoc { get; set; }
        public string DescVendDoc { get; set; }
        public string DctoAlt { get; set; }
        public decimal? ValorDebL2 { get; set; }
        public decimal? ValorCreL2 { get; set; }
        public decimal? ValorDebL2Me { get; set; }
        public decimal? ValorCreL2Me { get; set; }
        public decimal? BaseIvaretL2 { get; set; }
        public decimal? ValorDebL3 { get; set; }
        public decimal? ValorCreL3 { get; set; }
        public decimal? ValorDebL3Me { get; set; }
        public decimal? ValorCreL3Me { get; set; }
        public decimal? BaseIvaretL3 { get; set; }
        public string IndModulo { get; set; }
        public string DetalleAdi1 { get; set; }
        public string DetalleAdi2 { get; set; }
        public string DetalleAdi3 { get; set; }
        public string DetalleAdi4 { get; set; }
        public string DetalleAdi5 { get; set; }
        public string DetalleAdi6 { get; set; }
        public string DetalleAdi7 { get; set; }
        public string DetalleAdi8 { get; set; }
        public string DetalleAdi9 { get; set; }
        public string DetalleAdi10 { get; set; }
        public string CodigoEq { get; set; }
        public string IdCtaniv1Eq { get; set; }
        public string IdCtaniv2Eq { get; set; }
        public string IdCtaniv3Eq { get; set; }
        public string IdCtaniv4Eq { get; set; }
        public string IdCtaniv5Eq { get; set; }
        public string IdCtaniv6Eq { get; set; }
        public string IdCtaniv7Eq { get; set; }
        public string IdCtaniv8Eq { get; set; }
        public string UninegCta { get; set; }
        public string PrefProvDoc { get; set; }
        public string NroProvDoc { get; set; }
        public string UnidadNeg { get; set; }
    }
}
