using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class MovimientoInventario
    {
        public string LapsoDoc { get; set; }
        public string IdEmp { get; set; }
        public string DocInvCo { get; set; }
        public string DocInvTipo { get; set; }
        public string DocumentoInv { get; set; }
        public string DocumentoAlt { get; set; }
        public string IdTerc { get; set; }
        public string IdSuc { get; set; }
        public string FechaFc { get; set; }
        public string IdVendedor { get; set; }
        public string IndEs { get; set; }
        public string IdLocal { get; set; }
        public string IdItem { get; set; }
        public string IdExtItm { get; set; }
        public string IdTalla { get; set; }
        public string IdRefer { get; set; }
        public string IdCodbar { get; set; }
        public string IdConcepto { get; set; }
        public string IdMotivo { get; set; }
        public string UnimedCap { get; set; }
        public decimal? Cantidad1 { get; set; }
        public decimal? CostoUni { get; set; }
        public decimal? Costot { get; set; }
        public decimal? Cantidad2 { get; set; }
        public decimal? Peso { get; set; }
        public decimal? Volumen { get; set; }
        public string Lote { get; set; }
        public string FechaVctoLote { get; set; }
        public string Ubicacion { get; set; }
        public string IdCoMov { get; set; }
        public string IdCriter1 { get; set; }
        public string IdCriter2 { get; set; }
        public string IdCriter3 { get; set; }
        public string IdClater1 { get; set; }
        public string IdClater2 { get; set; }
        public string IdClater { get; set; }
        public string IdZona1 { get; set; }
        public string IdZona2 { get; set; }
        public string IdZona { get; set; }
        public string IdPais { get; set; }
        public string IdDpto { get; set; }
        public string IdCiudad { get; set; }
        public string IdTipo { get; set; }
        public string IdLinea1 { get; set; }
        public string IdLinea2 { get; set; }
        public string IdLinea { get; set; }
        public string IdLinea16 { get; set; }
        public string IdLinea36 { get; set; }
        public string IdLinea56 { get; set; }
        public string IdGrupo1 { get; set; }
        public string IdGrupo2 { get; set; }
        public string IdGrupo { get; set; }
        public string IdGrupo16 { get; set; }
        public string IdGrupo36 { get; set; }
        public string IdGrupo56 { get; set; }
        public string IdGrucon { get; set; }
        public string IdCricla1 { get; set; }
        public string IdCricla2 { get; set; }
        public string IdCricla3 { get; set; }
        public string IdCricla4 { get; set; }
        public string IdProcedencia { get; set; }
        public string Descripcion2 { get; set; }
        public decimal? FactorEmpaq { get; set; }
        public string UnimedEmpaq { get; set; }
        public string IdCtaDscto { get; set; }
        public string IdCtaIngre { get; set; }
        public string IdCtaInv { get; set; }
        public string IdCtaInvContra { get; set; }
        public string IdCcosto { get; set; }
        public string GrupoCcosto { get; set; }
        public string CodigoNiv1 { get; set; }
        public string CodigoNiv2 { get; set; }
        public string CodigoNiv3 { get; set; }
        public string IdProyecto { get; set; }
        public string NroReq { get; set; }
        public string IdOrides { get; set; }
        public decimal? CantTalla1 { get; set; }
        public decimal? CantTalla2 { get; set; }
        public decimal? CantTalla3 { get; set; }
        public decimal? CantTalla4 { get; set; }
        public decimal? CantTalla5 { get; set; }
        public decimal? CantTalla6 { get; set; }
        public decimal? CantTalla7 { get; set; }
        public decimal? CantTalla8 { get; set; }
        public decimal? CantTalla9 { get; set; }
        public decimal? CantTalla10 { get; set; }
        public string CargueCo { get; set; }
        public string CargueNro { get; set; }
        public string IdCoOp { get; set; }
        public string DocumentoOp { get; set; }
        public string LoteOp { get; set; }
        public string ReferenciaOp { get; set; }
        public string IdItemOp { get; set; }
        public string ReferItemOp { get; set; }
        public decimal? CostoMp { get; set; }
        public decimal? CostoMo { get; set; }
        public decimal? CostoInd { get; set; }
        public decimal? CostoSub { get; set; }
        public decimal? CostoOtr { get; set; }
        public decimal? CostoMpEst { get; set; }
        public decimal? CostoMoEst { get; set; }
        public decimal? CostoIndEst { get; set; }
        public decimal? CostoSubEst { get; set; }
        public decimal? CostoOtrEst { get; set; }
        public string IndConsumoEntrega { get; set; }
        public string Detalle1 { get; set; }
        public string Detalle2 { get; set; }
        public string Detalle3 { get; set; }
        public string Detalle4 { get; set; }
        public string IdGruloc { get; set; }
        public decimal? TasaCambio { get; set; }
        public decimal? TasaConver { get; set; }
        public string IdCargue { get; set; }
        public decimal? VlrNeto { get; set; }
        public string Detalle { get; set; }
        public string DetalleDoc { get; set; }
        public string FechaGen { get; set; }
        public string IdSerial { get; set; }
        public string DoctoOv { get; set; }
        public string LocalOrigDest { get; set; }
        public string AnoDoc { get; set; }
        public string DescOrigDest { get; set; }
        public string EnsambleRegOri { get; set; }
        public string NtdMovinDes { get; set; }
        public string IdTercProv { get; set; }
        public string OrigenDoc { get; set; }
        public string UsuarioIng { get; set; }
        public string UsuarioMod { get; set; }
        public decimal? VlrBruto { get; set; }
        public decimal? VlrLinea1 { get; set; }
        public decimal? VlrGlobal1 { get; set; }
        public decimal? VlrIva { get; set; }
        public decimal? VlrImpo { get; set; }
        public string TipoOc { get; set; }
        public string NroOc { get; set; }
        public string FechaOc { get; set; }
        public string TipoFp { get; set; }
        public string NroFp { get; set; }
        public string FechaFp { get; set; }
    }
}
