using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccess
{
    public partial class Terceros
    {
        public string Codigo { get; set; }
        public string Sucursal { get; set; }
        public string Descripcion { get; set; }
        public string Nit { get; set; }
        public string NitDv { get; set; }
        public string TipoTercero { get; set; }
        public string TipoIdentifica { get; set; }
        public string IndCli { get; set; }
        public string IndPro { get; set; }
        public string IndEmpl { get; set; }
        public string IndAcci { get; set; }
        public string IndVar { get; set; }
        public string IndInt { get; set; }
        public string IndTar { get; set; }
        public string IndPdv { get; set; }
        public string Estado { get; set; }
        public string FechaCreacion { get; set; }
        public string PaisCorresp { get; set; }
        public string DptoCorresp { get; set; }
        public string CiudadCorresp { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string Direccion3 { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string Barrio { get; set; }
        public string CodigoCiiu { get; set; }
        public string Email { get; set; }
        public string Establecimiento { get; set; }
        public string CliClase1 { get; set; }
        public string CliClase2 { get; set; }
        public string CliClase { get; set; }
        public string CliCo { get; set; }
        public string CliZona1 { get; set; }
        public string CliZona2 { get; set; }
        public string CliZona { get; set; }
        public string CliVendedor { get; set; }
        public string CliContacto { get; set; }
        public string CliCriterioNiv1 { get; set; }
        public string CliCriterioNiv2 { get; set; }
        public string CliCriterioNiv3 { get; set; }
        public string CliCalifica { get; set; }
        public string CliCondPago { get; set; }
        public string CliObserva { get; set; }
        public decimal? CliDGracia { get; set; }
        public decimal? CliCupoCre { get; set; }
        public decimal? CliDsctoGl { get; set; }
        public string CliIndBloCupo { get; set; }
        public string CliIndBloMora { get; set; }
        public string CliEstado { get; set; }
        public string CliLipre { get; set; }
        public string CliLides { get; set; }
        public string CliFormaPago { get; set; }
        public string CliRutaVis { get; set; }
        public string CliRutaTra { get; set; }
        public string CliPuntoEnv { get; set; }
        public string ProClase1 { get; set; }
        public string ProClase2 { get; set; }
        public string ProClase { get; set; }
        public string ProContacto { get; set; }
        public string ProCondPago { get; set; }
        public decimal? ProDGracia { get; set; }
        public decimal? ProCupoCre { get; set; }
        public string ProEstado { get; set; }
        public string ProObserva { get; set; }
        public string ProCptoFujo { get; set; }
        public string ProCalifica { get; set; }
        public string IndReteiva { get; set; }
        public string IndReteica { get; set; }
        public string IndReteotr { get; set; }
        public string IdPtoenv { get; set; }
        public string PtoenvDesc { get; set; }
        public string IndGranCont { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Nombres { get; set; }
        public string CiudadTercero { get; set; }
        public string IndLiqImptoC { get; set; }
        public string ProFormaPago { get; set; }
        public string TipoCuenta { get; set; }
        public string MetodoPago { get; set; }
        public string NroCtaBanco { get; set; }
        public string TitularCta { get; set; }
        public string CodBanco { get; set; }
        public string DescBanco { get; set; }
        public string FichaTecnica { get; set; }
        public string IndReterenta { get; set; }
        public string IndRegimenSimp { get; set; }
        public string MesNaci { get; set; }
        public string DiaNaci { get; set; }
        public string TipoDian { get; set; }
        public string ExigeChequePosf { get; set; }
        public string ExigeOc { get; set; }
        public string ObservacionC { get; set; }
        public decimal? DiasPpProv { get; set; }
        public decimal? DsctoPpProv { get; set; }
        public string DctoPpClien { get; set; }
        public string FechaUltPago { get; set; }
        public string TotDiasAtras { get; set; }
        public string NroPagoAtras { get; set; }
        public string TotDiasPago { get; set; }
        public string NroPagos { get; set; }
        public string FecUltVenta { get; set; }
        public decimal? VentaBruta { get; set; }
        public decimal? CostoVentas { get; set; }
        public decimal? Descuentos { get; set; }
        public decimal? FactMayorVlr { get; set; }
        public string NroVentas { get; set; }
        public string NroDevol { get; set; }
        public string NroChedev { get; set; }
        public string FecUltMvto { get; set; }
        public string PFechaUltPago { get; set; }
        public string PTotDiasAtras { get; set; }
        public string PNroPagoAtras { get; set; }
        public string PTotDiasPago { get; set; }
        public string PNroPagos { get; set; }
        public string PFecUltCompra { get; set; }
        public decimal? PComprasBrutas { get; set; }
        public string PNroCompras { get; set; }
        public string PNroDevol { get; set; }
        public string PFecUltMvto { get; set; }
        public string CliIndRemisionesC { get; set; }
        public string CliFtCampo1C { get; set; }
        public string CliFtCampo2C { get; set; }
        public string CodPostal { get; set; }
        public string GranContribC { get; set; }
        public string GranContribP { get; set; }
        public string IndReterentaP { get; set; }
        public string CliCarnet { get; set; }
        public string CliTipoCriterDesc1 { get; set; }
        public string CliTipoCriterDesc2 { get; set; }
        public string CliTipoCriterDesc3 { get; set; }
        public string CliFtCampo3C { get; set; }
        public string CliFtCampo4C { get; set; }
        public string CliFtCampo5C { get; set; }
        public string CliFtCampo6C { get; set; }
        public string CliFtCampo7C { get; set; }
        public string CliFtCampo8C { get; set; }
        public string CliFtCampo9C { get; set; }
        public string CliFtCampo10C { get; set; }
        public string NotifNombre { get; set; }
        public string NotifEmail { get; set; }
        public string NotifObser { get; set; }
    }
}
