using System;
using System.Collections.Generic;

namespace File.Repositorie.DataAccessPqa
{
    public partial class DetalleEntradasSalidas
    {
        public long IdEsdetalle { get; set; }
        public long IdRuInv { get; set; }
        public long IdMovimientoAlmacen { get; set; }
        public long? IdCacxp { get; set; }
        public long IdAlmacen { get; set; }
        public long IdProducto { get; set; }
        public long IdMedida { get; set; }
        public decimal Cantidad { get; set; }
        public decimal CostoUnitario { get; set; }
        public decimal Importe { get; set; }
        public decimal Descuento { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Impuesto { get; set; }
        public decimal TotalImporte { get; set; }
        public decimal? PorcentajeIva { get; set; }
        public string AgenteAduanal { get; set; }
        public string NoAduanaSeccion { get; set; }
        public string PedimentoImportacion { get; set; }
        public DateTime? FechaOperacion { get; set; }
        public long? IdCentroCosto { get; set; }
        public long? IdGasto { get; set; }
        public long? IdProductoCambiado { get; set; }
        public decimal? CantidadCambiada { get; set; }
        public decimal? CostoUnitarioCambiado { get; set; }
        public long? IdEsorigen { get; set; }
        public byte Status { get; set; }
        public long? IdTipoIeps { get; set; }
        public decimal ImporteIeps { get; set; }
        public long IdTasaIva { get; set; }
        public long? IdUsuarioCancelo { get; set; }
        public DateTime? FechaCancelo { get; set; }
        public string MotivoCancelo { get; set; }
        public long? IdUsuarioAlta { get; set; }
        public DateTime? RegistroAlta { get; set; }
        public long? IdUsuarioCambio { get; set; }
        public DateTime? RegistroCambio { get; set; }
        public Guid UiEsdetalle { get; set; }
        public long? IdCompra { get; set; }
        public long? IdVenta { get; set; }
        public long? IdSolicitudCompraDetalle { get; set; }
        public long? IdOrdenCompraDetalle { get; set; }
        public long? IdRequisicionDetalle { get; set; }
        public DateTime? FechaGeneracionArchivo { get; set; }
        public long? IdFabricante { get; set; }
        public byte Tipo { get; set; }
        public decimal ImporteRetencionIva { get; set; }
        public decimal ImporteRetencionIsr { get; set; }
        public decimal ImporteRetencionIeps { get; set; }
        public DateTime? FechaInicioDescargue { get; set; }
        public DateTime? FechaFinalDescargue { get; set; }
        public long? IdRuCxpcargo { get; set; }
        public long? IdRuCxpcargoAnticipo { get; set; }
        public decimal CostoProrrateo { get; set; }
        public byte TipoIeps { get; set; }
        public decimal ValorIeps { get; set; }
        public long? IdServicioGarantiaDetalleCostoAdicional { get; set; }
        public bool IsDeleted { get; set; }
        public string Concepto { get; set; }
        public long? IdEsdetalleVentaAutomatica { get; set; }
        public long? IdEsdetalleDevolucionAutomatica { get; set; }
        public long? IdRuCxpcargoCancelo { get; set; }
        public long? IdRuCxpcargoAnticipoCancelo { get; set; }
        public long? IdEscontrol { get; set; }
        public DateTime? FechaMovimiento { get; set; }
        public decimal? ValorCambio { get; set; }
        public long? IdKardex { get; set; }
        public long? IdListaPrecio { get; set; }
        public long? IdRuCxcabonoAnticipo { get; set; }
        public long? IdRuCxcabonoAnticipoCancelo { get; set; }
        public long? IdCxccargoAnticipo { get; set; }
        public long? IdIngreso { get; set; }
        public long? IdEmpresaSucursal { get; set; }
        public long? IdProductoVehiculo { get; set; }
        public long? IdGastoDepartamental { get; set; }
        public long? IdGastoDepartamentalCancelacion { get; set; }
        public long? IdIngresoDepartamental { get; set; }
        public long? IdIngresoDepartamentalCancelacion { get; set; }
        public long? IdRuCxcabonoAnticipoBanco { get; set; }
        public long? IdLibroBanco { get; set; }
        public long? IdContratoDetalleJr { get; set; }
        public string Temporada { get; set; }
        public decimal? ImporteImpuestoHospedaje { get; set; }
        public decimal? PorcentajeImpuestoHospedaje { get; set; }
        public DateTime? FechaAplicarKardex { get; set; }
        public long? IdKardexCancelacion { get; set; }
        public long? IdTasaIsh { get; set; }
        public long? IdRuGasto { get; set; }
        public decimal? PesoBruto { get; set; }
        public decimal? CantidadKilo { get; set; }
        public decimal? CostoUnitarioKilo { get; set; }
        public decimal? CantidadRollo { get; set; }
        public decimal? CostoUnitarioRollo { get; set; }
        public decimal? CantidadMetro { get; set; }
        public decimal? CostoUnitarioMetro { get; set; }
        public decimal? Ancho { get; set; }
        public decimal? Largo { get; set; }
        public decimal? Calibre { get; set; }
        public decimal? ConstanteDensidad { get; set; }
        public byte? TienePerforado { get; set; }
        public byte? Diametro { get; set; }
        public byte? TipoPerforacion { get; set; }
        public decimal? DistanciaPlantas { get; set; }
        public decimal? DistanciaHileras { get; set; }
        public long? IdPedidoDetalle { get; set; }
        public long? IdCxpabonoRedondeo { get; set; }
        public long? IdCxccargoPropina { get; set; }
        public decimal? DistanciaPlantasLineaCentral { get; set; }
        public byte? EnlazadaApedido { get; set; }
        public long? IdGastoCostoVenta { get; set; }
        public string Observaciones { get; set; }
        public byte? EnStock { get; set; }
        public long? IdClienteTimbre { get; set; }
        public long? IdEventoBuffet { get; set; }
    }
}
